language: java

sudo: false

addons:
  apt:
    packages:
      # Travis is running v6u34 which uses outdated ciphers.
      - oracle-java6-installer
      # Travis is running v8u31 which exposes problems with instrumentation of invokedynamic call sites.
      - oracle-java8-installer

branches:
  only:
    - master

matrix:
  include:
    - jdk: openjdk6
    - jdk: oraclejdk7
      env: TARGET=-Pjava7
    - jdk: oraclejdk8
      env: TARGET=-Pjava8

install: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: ./mvnw jacoco:prepare-agent verify jacoco:report $TARGET -Pintegration -Dnet.bytebuddy.test.travis=true -B -V

after_success:
  - ./mvnw coveralls:report
