language: java

sudo: false

branches:
  only:
    - master

matrix:
  include:
    - jdk: openjdk6
    - jdk: oraclejdk7
      env: TARGET=-Pjava7 -Pintegration
    - jdk: oraclejdk8
      env: TARGET=-Pjava8 -Pintegration
    #- jdk: oraclejdk9
    #  env: TARGET=-Pjava9 # Findbugs cannot currently process Java 9

install: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: ./mvnw jacoco:prepare-agent verify jacoco:report $TARGET -Dnet.bytebuddy.test.travis=true -B -V

after_success:
  - ./mvnw coveralls:report
