language: java

sudo: false

branches:
  only:
    - master

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

matrix:
  include:
    - jdk: oraclejdk8
      env: TARGET=-Pjava8
    - jdk: oraclejdk7
      env: TARGET=-Pjava7

script: mvn verify $TARGET -Pintegration

after_success:
  - mvn clean cobertura:cobertura coveralls:report -Pintegration
