version: 2
jobs:
  build:
    docker:
      - image: openjdk:8-jdk
    working_directory: ~/byte-buddy
    steps:
      - checkout
      - run: ./mvnw jacoco:prepare-agent verify jacoco:report -Pintegration -Dnet.bytebuddy.test.ci=true -B -V
