version: 2
jobs:
  jdk6:
    docker:
      - image: openjdk:6-jdk
    working_directory: ~/jdk6
    steps:
      - checkout
      - run: ./mvnw jacoco:prepare-agent verify jacoco:report -pl '!byte-buddy-gradle-plugin' -Pintegration -Dnet.bytebuddy.test.ci=true
  jdk7:
    docker:
      - image: openjdk:7-jdk
    working_directory: ~/jdk7
    steps:
      - checkout
      - run: ./mvnw jacoco:prepare-agent verify jacoco:report -pl '!byte-buddy-gradle-plugin' -Pintegration -Pjava7 -Dnet.bytebuddy.test.ci=true
  jdk8:
    docker:
      - image: openjdk:8-jdk
    working_directory: ~/jdk8
    steps:
      - checkout
      - run: ./mvnw jacoco:prepare-agent verify jacoco:report -pl '!byte-buddy-gradle-plugin' -Pintegration -Pjava8 -Dnet.bytebuddy.test.ci=true
  jdk9:
    docker:
      - image: maven:3.5.0-jdk-9
    working_directory: ~/jdk9
    steps:
      - checkout
      - run: mvn verify -pl '!byte-buddy-gradle-plugin' -Pjava9 -Dnet.bytebuddy.test.ci=true
workflows:
  version: 2
  all_versions:
    jobs:
      - jdk6
      - jdk7
      - jdk8
      - jdk9
