name: CI

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  schedule:
    - cron: "0 0 * * 1"

jobs:
  hotspot-legacy:
    name: HotSpot (legacy)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install JDK
        run: sudo apt install openjdk-6-jdk
      - name: Build project
        run: ./mvnw verify -Dnet.bytebuddy.test.ci=true -Pintegration
