name: CI

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macOS-10.14]
        java: [1.6.x, 1.7.x, 1.8.x, 9.x.x, 10.x.x, 11.x.x, 12.x.x, 13.x.x, 14.x.x]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        architecture: x64
    - name: Build project
      run: ./mvnw install -Dnet.bytebuddy.test.ci=true
