name: CI

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.14]
        java: [8, 11, 13, 14]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
        architecture: x64
    - name: Build project
      run: ./mvnw verify -Dnet.bytebuddy.test.ci=true -Pjava${{ matrix.version}}
      if: matrix.java < 13
    - name: Build project (without Gradle)
      run: ./mvnw verify -Dnet.bytebuddy.test.ci=true -Pjava${{ matrix.version}} -pl !byte-buddy-gradle-plugin
      if: matrix.java > 12
