name: CI

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  schedule:
    - cron: "0 0 * * 1"

jobs:
  hotspot-legacy:
    name: HotSpot (legacy)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install JDK
        run: |
          wget https://cdn.azul.com/zulu/bin/zulu6.22.0.3-jdk6.0.119-linux_amd64.deb
          sudo dpkg -i zulu6.22.0.3-jdk6.0.119-linux_amd64.deb
      - name: Build project
        run: ./mvnw verify -Dnet.bytebuddy.test.ci=true -Pintegration
