name: CI

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    name: Linux build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '9.x.x'
        architecture: x64
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Build project
      run: |
        ./mvnw install -Dnet.bytebuddy.test.ci=true
